[uwsgi]
chdir = /home/dvboxs
module = vboxs.wsgi:application
home = /home/env/vboxs
master = true
processes = 2
socket = /home/dvboxs/uwsgi.sock
chmod-socket = 666
vacuum = true
enable-threads = true
die-on-term = true
logto = /home/dvboxs/uwsgi.log
