# Generated by Django 5.0.4 on 2024-04-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_amount_paid_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'سفارش'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'جزيات سفارشات'},
        ),
    ]
