# Generated by Django 5.0.4 on 2024-05-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_tayid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bayane',
            field=models.BooleanField(default=False, verbose_name='پرداخت بیانه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tayid',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
    ]
