# Generated by Django 5.0.4 on 2024-05-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_ersal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ersal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
